name: Zip Creator

on:
  push:

jobs:
  create-zip:
    name: Build and Create Downloadable Zip
    runs-on: ubuntu-latest
    steps:
      - name: Install zip
        run: sudo apt install zip

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: web

      - name: Run build script
        run: bun run build
        working-directory: web

      - name: Bundle files
        run: |
          mkdir -p ./temp/ox_inventory
          mkdir -p ./temp/ox_inventory/locales/
          cp ./{fxmanifest.lua,init.lua,client.lua,server.lua} ./temp/ox_inventory
          cp ./{locales/en.json,locales/fr.json} ./temp/ox_inventory/locales
          cp -r ./{build,data,modules} ./temp/ox_inventory
          cd ./temp && zip -r ../ox_inventory.zip ./ox_inventory

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          automatic_release_tag: "latest"
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: 'Ready to download'
          prerelease: true
          files: ox_inventory.zip
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: StarlingCityDevelopment/resources
          event-type: update-resources
          client-payload: '{"res": "ox_inventory"}'
