name: Sync with upstream

on:
  schedule:
    - cron: "7,22,37,52 * * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync "${{ github.repository }}" \
            --source overextended/ox_inventory \
            --branch main